import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://183.82.251.239/en');
  await page.getByRole('link', { name: 'Sign In & Sign Up' }).click();
  await page.waitForTimeout(1000); // wait for the page to load
  await page.locator('label').filter({ hasText: 'Do BothSource what you need' }).dblclick();
  await page.getByRole('button', { name: 'Continue Continue' }).click();
  await page.getByRole('radio', { name: 'Unregistered Business Owned' }).check();
  await page.getByRole('button', { name: 'Continue Continue' }).click();
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByLabel('Business Location').selectOption('IN');
  await page.getByRole('button', { name: 'Continue Continue' }).selectOption('IN');
  await page.getByLabel('Business Location').click();
  await page.locator('div').filter({ hasText: 'Business DetailsCompliance' }).nth(3).click();
  await page.getByRole('button', { name: 'Continue Continue' }).click();
  await page.getByRole('textbox', { name: 'Full Name' }).click();
  await page.getByRole('textbox', { name: 'Full Name' }).fill('QATest');
  await page.getByRole('textbox', { name: 'Full Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email' }).fill('pepoqareports@gmail.com');
  await page.getByRole('textbox', { name: 'Date of Birth' }).fill('2020-01-31');
  await page.getByRole('spinbutton', { name: 'Personal ID Number' }).click();
  await page.getByRole('spinbutton', { name: 'Personal ID Number' }).fill('1');
  await page.getByRole('button', { name: 'Continue Continue' }).click();
  await page.getByRole('textbox', { name: 'Business Name(optional)' }).click();
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.locator('select[name="industry"]').selectOption('healthcare');
  await page.getByRole('textbox', { name: 'We sell sustainable home dé' }).selectOption('healthcare');
  await page.getByRole('textbox', { name: 'We sell sustainable home dé' }).fill('hello');
  await page.getByRole('button', { name: 'Continue Continue' }).click();
  await page.getByRole('button', { name: 'Continue Continue' }).click();
  await page.getByRole('textbox', { name: 'Business Phone Number' }).fill('8778085411');
  await page.getByRole('textbox', { name: 'Business Email' }).click();
  await page.getByRole('textbox', { name: 'Business Email' }).fill('pepoqareports@gmail.com');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').selectOption('IN');
  await page.getByRole('textbox', { name: 'Street Address' }).selectOption('IN');
  await page.locator('select[name="businessAddress.country"]').click();
  await page.getByRole('textbox', { name: 'Street Address' }).click();
  await page.getByRole('textbox', { name: 'Street Address' }).fill('128.nu');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.locator('select[name="businessAddress.cityTown"]').selectOption('Coimbatore');
  await page.getByRole('textbox', { name: 'Postal Code' }).selectOption('Coimbatore');
  await page.getByRole('textbox', { name: 'Postal Code' }).fill('642201');
  await page.getByRole('textbox', { name: 'We sell sustainable home dé' }).click();
  await page.getByRole('textbox', { name: 'We sell sustainable home dé' }).fill('test');
  await page.getByRole('button', { name: 'Continue Continue' }).click();
});