import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://183.82.251.239/en');
  await page.getByRole('link', { name: 'Sign In & Sign Up' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 96323-70046');
  await page.getByRole('button', { name: 'Continue with Phone' }).click();
  await page.locator('.forms-otp').first().click();
  await page.locator('.forms-otp').first().fill('5');
  await page.locator('input:nth-child(2)').first().fill('3');
  await page.locator('input:nth-child(3)').first().fill('5');
  await page.locator('div:nth-child(3) > input').first().fill('6');
  await page.locator('div:nth-child(3) > input:nth-child(2)').fill('1');
  await page.locator('div:nth-child(3) > input:nth-child(3)').fill('3');
  await page.locator('div').filter({ hasText: /^Sales$/ }).getByRole('img').click();
  await page.locator('span').filter({ hasText: 'Sourcing' }).first().click();
  await page.getByRole('link', { name: 'RFQ & Supplier Match' }).click();
  await page.getByRole('button', { name: 'Post Buying Request Post' }).click();
  await page.getByRole('textbox', { name: 'Enter Product Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Product Name' }).fill('Chips');
  await page.getByRole('button', { name: 'Browse Category' }).click();
  await page.getByText('Food').click();
  await page.getByText('Preserved').click();
  await page.getByText('Pakaged items').click();
  await page.getByRole('button', { name: 'Choose' }).click();
  await page.getByRole('button', { name: 'Write with AI' }).first().click();
  await page.getByRole('textbox', { name: 'Please indicate your detailed' }).click();
  await page.getByRole('button', { name: 'Write with AI' }).first().click();
  await page.getByRole('textbox', { name: 'Please indicate your detailed' }).click();
  await page.getByRole('textbox', { name: 'Please indicate your detailed' }).fill('Delicious chips');
  await page.getByRole('textbox', { name: 'Enter Additional Buying' }).click();
  await page.getByRole('button', { name: 'Write with AI' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Enter Additional Buying' }).click();
  await page.getByRole('textbox', { name: 'Enter Additional Buying' }).fill('TAsty');
  await page.getByRole('textbox', { name: 'Enter/generate your RFQ Title' }).click();
  await page.getByRole('textbox', { name: 'Enter/generate your RFQ Title' }).fill('Need Potato Chips');
  await page.locator('input[name="estOrderQuantity.quantity"]').click();
  await page.locator('input[name="estOrderQuantity.quantity"]').fill('');
  await page.locator('input[name="estOrderQuantity.quantity"]').click();
  await page.locator('input[name="estOrderQuantity.quantity"]').fill('10');
  await page.getByText('UnitsUnits').click();
  await page.getByRole('option', { name: 'Boxes' }).click();
  await page.locator('input[name="preferredUnitPrice.priceRange.minPrice"]').click();
  await page.locator('input[name="preferredUnitPrice.priceRange.minPrice"]').fill('100');
  await page.locator('input[name="preferredUnitPrice.priceRange.minPrice"]').press('Tab');
  await page.locator('input[name="preferredUnitPrice.priceRange.maxPrice"]').fill('200');
  await page.locator('input[name="preferredUnitPrice.priceRange.maxPrice"]').press('Tab');
  await page.getByRole('complementary').locator('div').filter({ hasText: /^Post Buying Request$/ }).click();
  await page.getByRole('button', { name: 'Select Currency' }).click();
  await page.getByRole('option', { name: 'Indian Rupee' }).click();
  await page.getByRole('combobox', { name: 'DD/MM/YY' }).click();
  await page.getByText('7', { exact: true }).click();
  await page.getByRole('button', { name: 'Additional Requirements (' }).click();
  await page.getByRole('button', { name: 'Additional Requirements (' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Additional Requirements (' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Additional Requirements (' }).press('ArrowDown');
  await page.getByText('Choose File').click();
  await page.getByRole('button', { name: 'Drag & Drop file from' }).setInputFiles('images.jpg');
  await page.getByRole('radio', { name: 'Nearby' }).check();
  await page.getByRole('region', { name: 'Additional Requirements (' }).getByRole('combobox').selectOption('IN');
  await page.getByRole('radio', { name: 'Within My Country' }).check();
  await page.getByRole('radio', { name: 'Nearby' }).check();
  await page.getByRole('radio', { name: 'Within My Country' }).check();
  await page.getByRole('radio', { name: 'International' }).check();
  await page.getByRole('radio', { name: 'Within My Country' }).check();
  await page.getByRole('radio', { name: 'International' }).check();
  await page.getByRole('radio', { name: 'Within My Country' }).check();
  await page.getByText('Preferred Sourcing RegionNearbyWithin My CountryInternationalSelect').click();
  await page.getByText('Preferred Sourcing RegionNearbyWithin My CountryInternational').click();
  await page.getByRole('radio', { name: 'Nearby' }).check();
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(3).selectOption('IN');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('combobox').nth(3).selectOption('Tezpur');
  await page.getByRole('radio', { name: 'Within My Country' }).selectOption('Tezpur');
  await page.getByRole('combobox').nth(2).check();
  await page.getByRole('combobox').nth(2).check();
  await page.getByRole('radio', { name: 'International' }).check();
  await page.getByText('Select Payment TermsSelect Payment Terms', { exact: true }).click();
  await page.getByRole('radio', { name: 'Nearby' }).check();
  await page.locator('span').filter({ hasText: /^Select$/ }).click();
  await page.locator('span').filter({ hasText: /^Select$/ }).click();
  await page.locator('span').filter({ hasText: /^Select Payment Terms$/ }).click();
  await page.locator('span').filter({ hasText: /^Select Payment Terms$/ }).click();
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(2).selectOption('IN');
  await page.getByRole('combobox').nth(3).selectOption('IN');
  await page.getByRole('combobox').nth(3).selectOption('Coimbatore');
  await page.getByRole('combobox').nth(3).selectOption('Coimbatore');
  await page.getByRole('combobox').nth(3).selectOption('Coimbatore');
  await page.getByRole('combobox').nth(3).selectOption('Coimbatore');
  await page.getByRole('combobox').nth(3).selectOption('Coimbatore');
  await page.getByRole('combobox').nth(3).selectOption('Coimbatore');
  await page.getByRole('combobox').nth(3).selectOption('Coimbatore');
  await page.getByRole('combobox').nth(3).selectOption('Coimbatore');
  await page.getByRole('combobox').nth(3).selectOption('Coimbatore');
  await page.getByRole('combobox').nth(3).selectOption('Coimbatore');
  await page.locator('span').filter({ hasText: /^Select$/ }).selectOption('Coimbatore');
  await page.getByRole('combobox').nth(2).click();
  await page.getByRole('combobox').nth(2).click();
  await page.getByRole('combobox').nth(2).click();
  await page.getByRole('combobox').nth(2).click();
  await page.getByRole('combobox').nth(2).click();
  await page.getByRole('combobox').nth(2).click();
  await page.locator('span').filter({ hasText: /^Select Payment Terms$/ }).click();
  await page.getByRole('option', { name: 'Net 90' }).click();
  await page.locator('span').filter({ hasText: /^Select$/ }).click();
  await page.getByRole('option', { name: 'Express' }).click();
  await page.getByRole('textbox', { name: 'e.g., Mumbai Port' }).click();
  await page.getByRole('textbox', { name: 'e.g., Mumbai Port' }).fill('Mumbai');
  await page.getByText('Select Shipping Method').click();
  await page.getByText('Select Shipping MethodSeaAirRoadRailCourierBuyer-ArrangedLocal Delivery').click();
  await page.getByText('Select Shipping MethodSeaAirRoadRailCourierBuyer-ArrangedLocal Delivery').click();
  await page.getByText('Select Shipping MethodSeaAirRoadRailCourierBuyer-ArrangedLocal Delivery').click();
  await page.getByText('Select Shipping MethodSeaAirRoadRailCourierBuyer-ArrangedLocal Delivery').click();
  await page.getByText('Select Shipping MethodSeaAirRoadRailCourierBuyer-ArrangedLocal Delivery').click();
  await page.getByText('Select Shipping MethodSeaAirRoadRailCourierBuyer-ArrangedLocal Delivery').click();
  await page.getByText('Toggle').first().click();
  await page.getByText('Toggle').first().click();
  await page.getByText('Toggle').nth(1).click();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.goto('http://183.82.251.239/en/app/sourcing-rfq');
  await page.locator('div').filter({ hasText: 'Buying RequestPost Buying' }).nth(2).click();
});