import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://183.82.251.239/en/authenticate');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('anusuya2011cse@gmail.com');
  await page.getByText('EmailUse Phone NumberWe’ll be sending code to verify your email.Continue with').click();
  await page.getByRole('button', { name: 'Continue with Email' }).click();
  await page.locator('.forms-otp').first().click();
  await page.getByRole('textbox', { name: '1 (702) 123-' }).click();
  await page.getByRole('textbox', { name: '1 (702) 123-' }).fill('+91 96323-70046');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('.forms-otp').first().click();
  await page.locator('.forms-otp').first().fill('8');
  await page.locator('input:nth-child(2)').first().fill('5');
  await page.locator('input:nth-child(3)').first().fill('8');
  await page.locator('div:nth-child(3) > input').first().fill('7');
  await page.locator('div:nth-child(3) > input:nth-child(2)').fill('2');
  await page.locator('div:nth-child(3) > input:nth-child(2)').click();
  await page.locator('div:nth-child(3) > input:nth-child(2)').fill('3');
  await page.locator('div:nth-child(3) > input:nth-child(3)').press('Tab');
  await page.locator('div:nth-child(3) > input:nth-child(3)').click();
  await page.locator('div:nth-child(3) > input:nth-child(3)').fill('1');
  await page.locator('div').filter({ hasText: /^Sales$/ }).locator('path').first().click();
  await page.getByRole('link', { name: 'Sell Offer' }).click();
  await page.getByRole('link', { name: 'Product I Sell' }).click();
  await page.getByRole('button', { name: 'Add Product Add Product' }).click();
  await page.getByRole('textbox', { name: 'Enter Product Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Product Name' }).fill('Phone');
  await page.getByRole('textbox', { name: 'Enter Text' }).click();
  await page.getByRole('button', { name: 'Write with AI' }).click();
  await page.getByRole('textbox', { name: 'Enter SKU/Model number' }).click();
  await page.getByRole('textbox', { name: 'Enter SKU/Model number' }).fill('PH_!233');
  await page.getByRole('textbox', { name: 'Enter SKU/Model number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter SKU/Model number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter SKU/Model number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter SKU/Model number' }).fill('PH_1233');
  await page.getByRole('textbox', { name: 'Enter Text' }).click();
  await page.getByRole('textbox', { name: 'Enter Text' }).fill('text');
  await page.locator('.c-f-b-top').click();
  await page.locator('.three-column-layout').click();
  await page.getByRole('combobox', { name: 'Select Ai Category' }).click();
  await page.getByRole('button', { name: 'Browse Category' }).click();
  await page.getByText('Electronics').click();
  await page.getByText('Mobile Phones').click();
  await page.getByText('Smartphones').click();
  await page.getByRole('button', { name: 'Choose', exact: true }).click();
  await page.getByText('Choose File').first().click();
  await page.getByRole('button', { name: 'Drag & Drop file from computer or Choose File Upload JPG, JPEG, PNG (Max 5MB)' }).setInputFiles('images.jpg');
  await page.getByText('Product InformationCompleted0%SKU: --Product NameMain ThumbnailMin. Order').click();
  await page.getByRole('button', { name: 'Save & Continue Later' }).click();
  await page.getByRole('button', { name: 'Save & Continue Later' }).click();
  await page.getByText('Choose File').click();
  await page.getByRole('button', { name: 'Drag & Drop file from' }).setInputFiles('_712020ef1309a5e8e344b9a0c4fc9c9a8efe9d-Onboarding-170725-053612.pdf');
  await page.getByText('Select CountrySelect Country').click();
  await page.locator('form div').filter({ hasText: 'Country of Origin Select' }).getByRole('textbox').click();
  await page.locator('form div').filter({ hasText: 'Country of Origin Select' }).getByRole('textbox').fill('India');
  await page.getByRole('option', { name: 'India', exact: true }).click();
  await page.getByRole('button', { name: 'Save & Continue Later' }).click();
  await page.getByRole('table').click();
  await page.getByText('All(3)Drafts(1)Archive(0)7 items selectedProduct NameNo. VariantscategoryStock').click();
  await page.getByText('All(3)Drafts(1)Archive(0)7 items selectedProduct NameNo. VariantscategoryStock').click();
  await page.locator('td:nth-child(10)').first().click();
  await page.getByRole('button', { name: 'View Details' }).click();
});